# Generated by Django 4.1.3 on 2022-12-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Sofia Center', 'Sofia Center'), ('Sofia Neighbourhood', 'Sofia Neighbourhood'), ('Sofia Municipality', 'Sofia Municipality')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_photo', models.URLField()),
                ('zone_name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('street_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('square_meters', models.PositiveIntegerField()),
                ('floors_number', models.PositiveIntegerField()),
                ('construction_date', models.DateField()),
                ('is_near_parking', models.BooleanField()),
                ('is_near_park', models.BooleanField()),
                ('is_near_metro', models.BooleanField()),
                ('date_of_publication', models.DateField()),
                ('house_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.location')),
            ],
            options={
                'ordering': ['-date_of_publication'],
            },
        ),
    ]
