# Generated by Django 4.1.4 on 2022-12-17 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='floors_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_photo',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='house',
            name='square_meters',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='zone_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
