# Generated by Django 4.1.3 on 2022-12-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-date_of_publication']},
        ),
    ]
