# Generated by Django 4.1.3 on 2022-12-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caiaabandoneduser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
