# Generated by Django 4.1.3 on 2022-12-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_project', models.CharField(choices=[('Residential building', 'Residential building'), ('Multifamily building', 'Multifamily building'), ('Office building', 'Office building'), ('Retail building', 'Retail building'), ('Industrial building', 'Industrial building'), ('Industrial building', 'Industrial building'), ('Hotel', 'Hotel'), ('Non-Governmental Organisation', 'Non-Governmental Organisation')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type_photo', models.URLField()),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projecttype')),
            ],
        ),
    ]
