# Generated by Django 4.1.4 on 2022-12-17 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_type_photo',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='type_of_project',
            field=models.CharField(choices=[('Residential building', 'Residential building'), ('Multifamily building', 'Multifamily building'), ('Co-working space', 'Co-working space'), ('Retail building', 'Retail building'), ('Industrial building', 'Industrial building'), ('Hotel', 'Hotel'), ('City garden', 'City garden'), ('Urban farm', 'Urban farm'), ('Non-Governmental Organisation', 'Non-Governmental Organisation')], max_length=40, unique=True),
        ),
    ]
