# Generated by Django 4.1.3 on 2022-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='type_of_project',
            field=models.CharField(choices=[('Residential building', 'Residential building'), ('Multifamily building', 'Multifamily building'), ('Office building', 'Office building'), ('Retail building', 'Retail building'), ('Industrial building', 'Industrial building'), ('Hotel', 'Hotel'), ('Non-Governmental Organisation', 'Non-Governmental Organisation')], max_length=40),
        ),
    ]
